# Generated by Django 5.2.6 on 2025-10-17 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_blogpost_likes_alter_blogpost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_posts_disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
