# Generated by Django 5.2.6 on 2025-10-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='Click Above to Read More...', max_length=255),
        ),
    ]
