# Generated by Django 5.2.7 on 2025-10-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_blogpost_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
